var isHumanClickPv=false;function addEventClickPv(f,j,e,i){if(f.addEventListener){f.addEventListener(j,e,i);return true}else if(f.attachEvent)return f.attachEvent("on"+j,e);f["on"+j]=e}function mouseoverHandlerClickPv(){isHumanClickPv=true}function keydownHandlerClickPv(f){if(f.keyCode=="37"||f.keyCode=="38"||f.keyCode=="39"||f.keyCode=="40")isHumanClickPv=true}addEventClickPv(document,"mouseover",mouseoverHandlerClickPv,false);addEventClickPv(document,"mousemove",mouseoverHandlerClickPv,false);
addEventClickPv(document,"keydown",keydownHandlerClickPv,false);var ClickPvTrack;
this.ClickPvTrack||(ClickPvTrack=function(){function f(d){var g=new Image(1,1);g.onLoad=function(){};g.src=d}function j(){try{if(top!=this)return false;if(self.frameElement&&self.frameElement.tagName=="IFRAME")return false;return true}catch(d){return false}}this.ckpid=this.spid=this.bdid=this.pbid=this.cpid=this.cid=this.sid=0;this.pid=this.bid=this.scid="0";this.location=this.referrer=this.cpurl="";this.p1=0;var e="",i=document,o=window,h=o.location.hostname,k=o.encodeURIComponent||escape,c=this;
this.track=function(){if(isHumanClickPv){var d;d=e==""?false:true;if(d&&j()){d=e+"?v=1.0";var g="&sid="+c.sid+"&cid="+c.cid+"&cpid="+c.cpid+"&pbid="+c.pbid+"&bdid="+c.bdid+"&spid="+c.spid+"&ckpid="+c.ckpid+"&scid="+c.scid+"&bid="+c.bid+"&pid="+c.pid+"&i=",a;if(c.referrer!="")a=c.referrer;else{a="";try{a=top.document.referrer}catch(x){if(parent)try{a=parent.document.referrer}catch(p){a=""}}if(a==="")a=i.referrer}d+=g+k(a)+"&k="+k(c.location!=""?c.location:i.location.href)+"&d="+(new Date).getMilliseconds()+
"&cpurl="+k(c.cpurl)+"&p1="+c.p1;f(d)}}else setTimeout(arguments.callee,0)};(function(){for(var d=["pcpop.com","guomii.com"],g=["it168.com","qudao168.com","chinaunix.com","chinaunix.net","itpub.net","ixpub.net","igeek.com.cn","afjk.com","app111.com","mobpub.net","jimi168.com","feng91.com","bnxsj.com","pv.com","gengpianyi.com"],a=0;a<d.length;a++)if(h.indexOf(d[a])>-1){e="http://count.pcpop.com/ClickPvCount.ashx";if(h.indexOf("tu.pcpop.com")>-1){if("undefined"!=typeof click_channelid)c.p1=click_channelid}else if("undefined"!=
typeof channelId)c.p1=channelId;c.sid=h=="m.pcpop.com"?3:1;return}for(a=0;a<g.length;a++)if(h.indexOf(g[a])>-1){e="http://stat.it168.com/ClickPvCount.ashx";if("undefined"!=typeof click_channelid)c.p1=click_channelid;c.sid=h=="e.it168.com"||h=="p.it168.com"||h=="s.it168.com"||h=="m.it168.com"?3:2;break}})()});
function ArticleTruePV(f){function j(){var b="";try{b=top.document.referrer}catch(F){if(parent)try{b=parent.document.referrer}catch(s){b=""}}if(b==="")b=g.referrer;return b}function e(b,F,s,G,H,K){var t;if(s){t=new Date;t.setTime(t.getTime()+s*6E4)}g.cookie=b+"="+window.encodeURIComponent(F)+(s?";expires="+t.toGMTString():"")+";path="+(G?G:"/")+(H?";domain="+H:"")+(K?";secure":"")}function i(b){return(b=RegExp("(^|;)[ ]*"+b+"=([^;]*)").exec(g.cookie))?window.decodeURIComponent(b[2]):""}function o(){var b=
i(y);if(b!=""){b=b.split(".");if(b.length==5){q=parseInt(b[0]);z=parseInt(b[1]);u=parseInt(b[2]);v=parseInt(b[3]);r=parseInt(b[4]);b=i(w);if(b!="")m=parseInt(b);A=i(B)}}}function h(){var b;b=Math.round((new Date).getTime()/1E3);if(q==0){q=k();u=z=b}else u=v;v=b;if(A==""){m=k();r=1}else if(i(w)==""){m=k();r=1}else{m=parseInt(A);r+=1}b=q+"."+z+"."+u+"."+v+"."+r;if(n==""){e(y,b,I);e(w,m,J);e(B,m)}else{e(y,b,I,"/",n);e(w,m,J,"/",n);e(B,m,"","/",n)}}function k(){return Math.round(Math.random()*2147483647)}
function c(){try{if(top!=this)return false;if(self.frameElement&&self.frameElement.tagName=="IFRAME")return false;return true}catch(b){return false}}var d="",g=document,a=window.location.hostname,x="",p=0;x=this.location!=""?this.location:g.location.href;for(var n="",C="",D=["pcpop.com","guomii.com"],E=["it168.com","qudao168.com","chinaunix.com","chinaunix.net","itpub.net","ixpub.net","igeek.com.cn","afjk.com","app111.com","mobpub.net","jimi168.com","feng91.com","bnxsj.com"],l=0;l<D.length;l++)if(a.indexOf(D[l])>
-1){n=D[l];d="http://count.pcpop.com/ArticleTruePV.ashx";C="pop_userid";p=1;break}if(p==0)for(l=0;l<E.length;l++)if(a.indexOf(E[l])>-1){n=E[l];d="http://stat.it168.com/ArticleTruePV.ashx";C="sso_username_utf8";p=2;break}var y="__articlepta",I=1051200,q=0,z=0,u=0,v=0,r=1,w="__articlepts",m=0,J=20,B="__articleptb",A;if(isHumanClickPv){if(a=function(){if(d=="")return false;if(n=="")return false;if(C=="")return false;return true}())if(a=c())try{o();h();a=true}catch(L){a=false}if(a){a=new Image(1,1);a.onLoad=
function(){};a.src=d+"?siteid="+p+"&articletype="+f+"&httplink="+window.encodeURIComponent(x)+"&vid="+q+"&referrer="+window.encodeURIComponent(j())}}else setTimeout(arguments.callee,0)}function SendClick(f,j,e,i,o,h,k,c,d,g){var a=new ClickPvTrack;a.cid=f;a.cpid=j;a.pbid=e;a.bdid=i;a.spid=o;a.ckpid=h;a.scid=k;a.bid=c;a.pid=d;a.cpurl=g;a.track()};
